-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.assessment_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assigned_to uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assignment_type text NOT NULL DEFAULT 'primary'::text CHECK (assignment_type = ANY (ARRAY['primary'::text, 'secondary'::text, 'reviewer'::text, 'approver'::text])),
  assignment_status text NOT NULL DEFAULT 'assigned'::text CHECK (assignment_status = ANY (ARRAY['assigned'::text, 'accepted'::text, 'in_progress'::text, 'completed'::text, 'rejected'::text, 'cancelled'::text])),
  due_date timestamp with time zone,
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  estimated_hours numeric,
  actual_hours numeric,
  assignment_notes text,
  completion_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  completed_at timestamp with time zone,
  assessment_id uuid,
  CONSTRAINT assessment_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_assignments_new_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_assignments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT assessment_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.assessment_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid NOT NULL,
  previous_status text,
  new_status text NOT NULL CHECK (new_status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'requires_remediation'::text])),
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT assessment_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_status_history_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  scf_control_id text,
  scf_ao_id text,
  assessment_type text NOT NULL CHECK (assessment_type = ANY (ARRAY['manual'::text, 'automated'::text, 'integrated'::text])),
  assessment_method text NOT NULL DEFAULT 'manual'::text CHECK (assessment_method = ANY (ARRAY['manual'::text, 'automated'::text, 'ai_assisted'::text])),
  assessment_status text NOT NULL DEFAULT 'not_started'::text CHECK (assessment_status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'requires_remediation'::text])),
  assessment_result text CHECK (assessment_result = ANY (ARRAY['pass'::text, 'fail'::text, 'partial'::text, 'not_applicable'::text, 'not_tested'::text, 'met'::text, 'not_met'::text, 'partially_met'::text])),
  confidence_level text CHECK (confidence_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  risk_rating text CHECK (risk_rating = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  implementation_status text DEFAULT 'not_implemented'::text CHECK (implementation_status = ANY (ARRAY['not_implemented'::text, 'planned'::text, 'in_progress'::text, 'implemented'::text, 'needs_review'::text])),
  assessment_frequency text DEFAULT 'annual'::text CHECK (assessment_frequency = ANY (ARRAY['continuous'::text, 'monthly'::text, 'quarterly'::text, 'semi_annual'::text, 'annual'::text, 'biennial'::text])),
  assessment_notes text,
  assessment_summary text,
  remediation_plan text,
  business_impact text,
  remediation_timeline text,
  ai_reasoning text,
  deficiencies_identified ARRAY,
  recommendations ARRAY,
  testing_procedures ARRAY,
  validation_rules_applied jsonb,
  sample_size integer,
  population_size integer,
  assigned_to uuid,
  reviewed_by uuid,
  approved_by uuid,
  integration_source_id uuid,
  integration_source_type text,
  integration_timestamp timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  approved_at timestamp with time zone,
  next_assessment_due timestamp with time zone,
  evidence_id uuid,
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT assessments_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT assessments_scf_ao_id_fkey FOREIGN KEY (scf_ao_id) REFERENCES public.scf_assessment_objectives(scf_ao_id),
  CONSTRAINT assessments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT assessments_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT assessments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT assessments_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.evidence(id)
);
CREATE TABLE public.compliance_drift_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  integration_connection_id uuid,
  scf_control_id text,
  drift_type text NOT NULL CHECK (drift_type = ANY (ARRAY['degraded'::text, 'improved'::text, 'new_finding'::text, 'resolved'::text])),
  previous_status text,
  current_status text,
  impact_level text DEFAULT 'medium'::text CHECK (impact_level = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  change_details jsonb NOT NULL,
  detection_timestamp timestamp without time zone DEFAULT now(),
  resolved_at timestamp without time zone,
  resolved_by uuid,
  resolution_notes text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT compliance_drift_events_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_drift_events_integration_connection_id_fkey FOREIGN KEY (integration_connection_id) REFERENCES public.integration_connections(id),
  CONSTRAINT compliance_drift_events_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT compliance_drift_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT compliance_drift_events_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  scf_control_id text,
  evidence_type text NOT NULL CHECK (evidence_type = ANY (ARRAY['document'::text, 'screenshot'::text, 'policy'::text, 'procedure'::text, 'log'::text, 'certificate'::text, 'configuration'::text, 'other'::text, 'aws'::text, 'azure'::text, 'gcp'::text, 'github'::text, 'okta'::text, 'supabase'::text])),
  collection_method text NOT NULL DEFAULT 'manual'::text CHECK (collection_method = ANY (ARRAY['manual'::text, 'automated'::text, 'integrated'::text])),
  erl_id text,
  erl_global_id text,
  file_name text,
  file_path text,
  file_size bigint,
  file_type text,
  version integer DEFAULT 1,
  description text,
  evidence_status text NOT NULL DEFAULT 'pending'::text CHECK (evidence_status = ANY (ARRAY['pending'::text, 'submitted'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'outdated'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'skipped'::text])),
  integration_connection_id uuid,
  data_source text,
  evidence_data jsonb,
  processed_content text,
  confidence_score numeric CHECK (confidence_score IS NULL OR confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  submitted_by uuid,
  reviewed_by uuid,
  approved_by uuid,
  rejection_reason text,
  replaces_evidence_id uuid,
  outdated_at timestamp with time zone,
  outdated_by integer,
  extracted_content text,
  content_extracted_at timestamp with time zone,
  content_extraction_status text DEFAULT 'pending'::text CHECK (content_extraction_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'skipped'::text])),
  storage_path text,
  evidence_group_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  approved_at timestamp with time zone,
  collection_timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT evidence_pkey PRIMARY KEY (id),
  CONSTRAINT evidence_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT evidence_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT evidence_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT evidence_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT evidence_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT evidence_replaces_evidence_id_fkey FOREIGN KEY (replaces_evidence_id) REFERENCES public.evidence(id)
);
CREATE TABLE public.integration_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  provider_id text,
  connection_name text NOT NULL,
  connection_config jsonb NOT NULL,
  credentials_encrypted jsonb NOT NULL,
  connection_status text DEFAULT 'active'::text CHECK (connection_status = ANY (ARRAY['active'::text, 'inactive'::text, 'error'::text, 'expired'::text])),
  last_sync_at timestamp without time zone,
  last_error text,
  sync_frequency text DEFAULT 'daily'::text CHECK (sync_frequency = ANY (ARRAY['real-time'::text, 'hourly'::text, 'daily'::text, 'weekly'::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT integration_connections_pkey PRIMARY KEY (id),
  CONSTRAINT integration_connections_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.integration_providers(provider_id),
  CONSTRAINT integration_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.integration_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id text NOT NULL UNIQUE,
  provider_name text NOT NULL,
  provider_type text NOT NULL,
  supported_services jsonb NOT NULL DEFAULT '[]'::jsonb,
  connection_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT integration_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.integration_sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  integration_connection_id uuid,
  sync_type text NOT NULL,
  sync_status text NOT NULL CHECK (sync_status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  records_processed integer DEFAULT 0,
  evidence_created integer DEFAULT 0,
  assessments_completed integer DEFAULT 0,
  errors_encountered integer DEFAULT 0,
  sync_duration_ms integer,
  error_details jsonb,
  started_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT integration_sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT integration_sync_logs_integration_connection_id_fkey FOREIGN KEY (integration_connection_id) REFERENCES public.integration_connections(id)
);
CREATE TABLE public.scf_assessment_objectives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scf_control_id text NOT NULL,
  scf_ao_id text NOT NULL UNIQUE,
  assessment_objective text NOT NULL,
  origin text,
  notes_errata text,
  scf_baseline_aos boolean DEFAULT false,
  dhs_ztcf_aos boolean DEFAULT false,
  nist_800_53_r5_aos boolean DEFAULT false,
  nist_800_171_r2_aos boolean DEFAULT false,
  nist_800_171_r3_aos boolean DEFAULT false,
  nist_800_172_aos boolean DEFAULT false,
  asset_type text,
  assessment_procedure text,
  expected_results text,
  assessment_status text CHECK (assessment_status IS NULL OR (assessment_status = ANY (ARRAY['met'::text, 'not_met'::text, 'not_tested'::text, 'not_applicable'::text]))),
  inherited boolean DEFAULT false,
  assessment_frequency text,
  last_date_assessed date,
  assessment_performed_by text,
  scf_version text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_assessment_objectives_pkey PRIMARY KEY (id),
  CONSTRAINT scf_assessment_objectives_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id)
);
CREATE TABLE public.scf_authoritative_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  geography text NOT NULL,
  mapping_column_header text NOT NULL,
  source_organization text NOT NULL,
  authoritative_source text NOT NULL,
  strm_url text,
  source_url text,
  scf_version text NOT NULL,
  import_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_authoritative_sources_pkey PRIMARY KEY (id),
  CONSTRAINT scf_authoritative_sources_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.scf_imports(id)
);
CREATE TABLE public.scf_control_evidence_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scf_control_id text NOT NULL,
  evidence_request_id uuid NOT NULL,
  relationship_type text DEFAULT 'required'::text CHECK (relationship_type = ANY (ARRAY['required'::text, 'optional'::text, 'supplementary'::text])),
  priority integer DEFAULT 100,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT scf_control_evidence_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_control_evidence_control FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT fk_control_evidence_request FOREIGN KEY (evidence_request_id) REFERENCES public.scf_evidence_request_list(id),
  CONSTRAINT fk_control_evidence_created_by FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.scf_control_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scf_control_id text,
  provider_id text,
  service_name text NOT NULL,
  check_type text NOT NULL,
  validation_rules jsonb NOT NULL,
  priority integer DEFAULT 100,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT scf_control_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT scf_control_integrations_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT scf_control_integrations_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.integration_providers(provider_id)
);
CREATE TABLE public.scf_control_mappings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  control_id text,
  framework_id uuid,
  framework_control_id text NOT NULL,
  mapping_type text DEFAULT 'direct'::text,
  confidence_score numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_control_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT scf_control_mappings_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT scf_control_mappings_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES public.scf_frameworks(id)
);
CREATE TABLE public.scf_control_risk_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scf_control_id text NOT NULL,
  risk_id text NOT NULL,
  relevance_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_control_risk_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT scf_control_risk_mappings_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT scf_control_risk_mappings_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.scf_risks(id)
);
CREATE TABLE public.scf_control_threat_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scf_control_id text NOT NULL,
  threat_id text NOT NULL,
  impact_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_control_threat_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT scf_control_threat_mappings_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id),
  CONSTRAINT scf_control_threat_mappings_threat_id_fkey FOREIGN KEY (threat_id) REFERENCES public.scf_threats(id)
);
CREATE TABLE public.scf_controls (
  id text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  domain_id text,
  principle text,
  control_questions ARRAY,
  guidance_micro text,
  guidance_small text,
  guidance_medium text,
  guidance_large text,
  guidance_enterprise text,
  applies_to_people boolean DEFAULT false,
  applies_to_process boolean DEFAULT false,
  applies_to_technology boolean DEFAULT false,
  applies_to_governance boolean DEFAULT false,
  risk_ids ARRAY,
  threat_ids ARRAY,
  assessment_objectives ARRAY,
  scf_version text NOT NULL,
  import_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_vector tsvector,
  current_maturity_level integer,
  target_maturity_level integer,
  CONSTRAINT scf_controls_pkey PRIMARY KEY (id),
  CONSTRAINT scf_controls_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES public.scf_domains(id),
  CONSTRAINT scf_controls_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.scf_imports(id)
);
CREATE TABLE public.scf_domains (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  control_count integer DEFAULT 0,
  scf_version text NOT NULL,
  import_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  principle_intent text,
  CONSTRAINT scf_domains_pkey PRIMARY KEY (id),
  CONSTRAINT scf_domains_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.scf_imports(id)
);
CREATE TABLE public.scf_evidence_request_list (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erl_id text NOT NULL,
  area_of_focus text NOT NULL,
  documentation_artifact text NOT NULL,
  artifact_description text NOT NULL,
  scf_version text NOT NULL,
  import_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_evidence_request_list_pkey PRIMARY KEY (id),
  CONSTRAINT scf_evidence_request_list_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.scf_imports(id)
);
CREATE TABLE public.scf_frameworks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  framework_name text NOT NULL,
  framework_version text,
  source_url text,
  mapping_type text NOT NULL,
  total_mappings integer DEFAULT 0,
  scf_version text NOT NULL,
  import_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_frameworks_pkey PRIMARY KEY (id),
  CONSTRAINT scf_frameworks_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.scf_imports(id)
);
CREATE TABLE public.scf_imports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  filename text NOT NULL,
  file_size bigint NOT NULL,
  scf_version text NOT NULL,
  import_status text NOT NULL DEFAULT 'processing'::text,
  total_controls integer DEFAULT 0,
  total_domains integer DEFAULT 0,
  total_frameworks integer DEFAULT 0,
  total_mappings integer DEFAULT 0,
  errors ARRAY,
  warnings ARRAY,
  imported_by uuid,
  imported_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT scf_imports_pkey PRIMARY KEY (id),
  CONSTRAINT scf_imports_imported_by_fkey FOREIGN KEY (imported_by) REFERENCES auth.users(id)
);
CREATE TABLE public.scf_maturity_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scf_control_id text NOT NULL,
  level_0_description text,
  level_1_description text,
  level_2_description text,
  level_3_description text,
  level_4_description text,
  level_5_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_maturity_levels_pkey PRIMARY KEY (id),
  CONSTRAINT scf_maturity_levels_scf_control_id_fkey FOREIGN KEY (scf_control_id) REFERENCES public.scf_controls(id)
);
CREATE TABLE public.scf_principles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  number integer NOT NULL,
  domain_code text NOT NULL,
  domain_name text NOT NULL,
  principle_name text NOT NULL,
  principle_intent text NOT NULL,
  scf_version text NOT NULL,
  import_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_principles_pkey PRIMARY KEY (id),
  CONSTRAINT scf_principles_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.scf_imports(id),
  CONSTRAINT scf_principles_domain_code_fkey FOREIGN KEY (domain_code) REFERENCES public.scf_domains(id)
);
CREATE TABLE public.scf_risks (
  id text NOT NULL,
  risk_grouping text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  nist_csf_function text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_risks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scf_threats (
  id text NOT NULL,
  threat_grouping text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scf_threats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text,
  organization text,
  role text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);