export const selectors = {
  auth: {
    form: "auth-form",
    signInTab: "auth-tab-signin",
    signUpTab: "auth-tab-signup",
    signInEmailInput: "signin-email-input",
    signInPasswordInput: "signin-password-input",
    signInSubmitButton: "signin-submit-button",
    signUpEmailInput: "signup-email-input",
    signUpPasswordInput: "signup-password-input",
  },
  dashboard: {
    overviewCard: "dashboard-overview-card",
    overviewTitle: "dashboard-overview-title",
    coverageModeBadge: "dashboard-coverage-mode-badge",
    coverageSummaryCard: "coverage-summary-card",
    frameworkFilterTrigger: "framework-filter-trigger",
    clearFrameworkFocusButton: "clear-framework-focus-button",
    uploadEvidenceButton: "dashboard-upload-evidence-button",
    viewPriorityControlsButton: "view-priority-controls-button",
    uploadDialog: "dashboard-upload-dialog",
    navTabOverview: "dashboard-nav-tab-overview",
    navTabEvidence: "dashboard-nav-tab-evidence",
    navTabAssessments: "dashboard-nav-tab-assessments",
    navTabAnalytics: "dashboard-nav-tab-analytics",
    navTabFrameworks: "dashboard-nav-tab-frameworks",
    analyticsPurposeCard: "analytics-purpose-card",
    analyticsActivityCard: "analytics-activity-card",
    analyticsControlsWithEvidenceCard: "analytics-controls-with-evidence-card",
    analyticsDomainCoverageCard: "analytics-domain-coverage-card",
    analyticsDomainCoverageTable: "analytics-domain-coverage-table",
    analyticsExportCard: "analytics-export-card",
  },
  assessments: {
    openExplainerButton: "assessments-open-explainer",
    inlineExplainer: "assessments-inline-explainer",
    controlRow: "assessment-result-card",
    rowDetailButton: "assessment-row-detail-button",
    rowVerdict: "assessment-result-verdict",
    detailDialog: "assessment-detail-dialog",
    detailRunGroup: "assessment-detail-run-group",
    exportButton: "assessments-export-button",
    exportCsv: "assessments-export-csv",
    exportJson: "assessments-export-json",
  },
  evidence: {
    row: "evidence-row",
    viewAction: "evidence-view-action",
    detailDialog: "evidence-detail-dialog",
    detailFileName: "evidence-detail-file-name",
    detailControls: "evidence-detail-controls",
    detailRecordList: "evidence-detail-record-list",
    importOpen: "evidence-import-open",
    importDialog: "evidence-import-dialog",
    importFile: "evidence-import-file",
    importPreviewButton: "evidence-import-preview-button",
    importCommitButton: "evidence-import-commit-button",
    importSummary: "evidence-import-summary",
    importPreview: "evidence-import-preview",
    importRow: "evidence-import-row",
    importError: "evidence-import-error",
    importSuccess: "evidence-import-success",
  },
  upload: {
    openSmartUploadButton: "open-smart-upload-button",
    dialog: "smart-upload-dialog",
    title: "smart-upload-title",
    documentationArtifactCombobox: "documentation-artifact-combobox",
    evidenceTypeSelectTrigger: "evidence-type-select-trigger",
    documentUploadInput: "document-upload-input",
    resultVerdict: "assessment-result-verdict",
    startAiAssessmentButton: "start-ai-assessment-button",
    approveAssessmentButton: "approve-assessment-button",
    rejectAssessmentButton: "reject-assessment-button",
    artifactMappingLink: "artifact-mapping-link",
    retryFailedControlsButton: "retry-failed-controls-button",
  },
  public: {
    navHeader: "primary-navigation",
    tryItOutHeading: "try-it-out-heading",
    tryItOutSummary: "try-it-out-summary",
    tryItOutLiveUploadSection: "try-it-out-live-upload-section",
    frameworkResultsCount: "framework-results-count",
    frameworkSearchInput: "framework-search-input",
    frameworkCardLink: "framework-card-link",
    frameworkCardTitle: "framework-card-title",
    frameworkCardDescription: "framework-card-description",
    frameworkDetailHeading: "framework-detail-heading",
    frameworkDetailMappings: "framework-detail-mappings",
  },
  inbox: {
    page: "compliance-inbox-page",
    itemCard: "inbox-item-card",
    actionButton: "inbox-action-button",
    postureSummary: "inbox-posture-summary",
    emptyState: "inbox-empty-state",
    summaryCard: "inbox-summary-card",
  },
  freshness: {
    dot: "evidence-freshness-dot",
  },
  impactPreview: {
    banner: "impact-preview-banner",
    score: "impact-preview-score",
  },
} as const;
